### ISSUE TITLE
Ch 7 page 181 Listing 7-8; DVGA introspection query to fetch Directive names & args, what response should I expect?

### ISSUE THREAD

**Issue by mrbiggleswirth** [dolevf/Black-Hat-GraphQL#10]
Hello Graphers,
I'm trying to detect the Authorization layer in the **DVGA** app by finding **SCHEMA DIRECTIVES** with this introspection query. But I seem to only receive some short general description response. Which doesn't give me any hints on what directives exist in DVGA such as `@auth`, `@authorize`, `@authorization`, `@authz`, and others.

What data response should I expect to see? When running this introspection query on the DVGA app.

**Listing 7-8**
```graphql
query {
  __schema {
    directives {
      name
      args {
        name
      }
    }
  }
}
```

**Comment by dolevf** [comment]
Hi there!

Your query is fine. DVGA itself doesn't implement authorization using directives, so you won't find any relevant directive names that suggest authorization is in place.

**Comment by mrbiggleswirth** [comment]
Thanks, I thought I might have missed to include some secret key, or failed to perform some WAF bypass.
