### ISSUE TITLE
Chapter 2  - InQL Installation

### ISSUE THREAD

**Issue by ItBeginsWCC** [dolevf/Black-Hat-GraphQL#11]
Hello, 

I have run into some issues while following the book on Chapter 2 for installing InQL. I have follow the steps (below) that are provided on the book. However, once i cloned i repo, i realized that the setup.py is under a python direction so i need to CD into that. Then, once i run the following command `sudo python3 setup.py install` i got some errors about that do not use directly setup.py and when command completes and when i try to see if InQL is install i get an error that it does not exists. I have look into the README of the repo and i do not see anything to install locally on the termimal, unless i miss this. On the other end, i have found a pip package called `pip install inql`. I wonder if this is install process was previously working or if there other ways around that we can follow the book as the book states that we will be using InQL later in the book. I did not know where else to post this Q&A. I am going through the book in the oreilly platform

```
Let’s install InQL. Open the terminal and enter the following commands:

# cd ~
# git clone https://github.com/doyensec/inql.git
# cd inql
# sudo python3 setup.py install
```

**Comment by dolevf** [comment]
Hi there,

Thanks for opening this issue. Indeed, InQL has gone through some changes and it broke the installation. I've put a comment under the Errata section on how to get the working version: https://github.com/dolevf/Black-Hat-GraphQL/blob/master/README.md#notes
