### ISSUE TITLE
Why Inql Showing Error When Version Greater than V4.0.7

### ISSUE THREAD

**Issue by RithvikTechnologies** [dolevf/Black-Hat-GraphQL#12]
Hi Bro,

Before reading this tool update, I cloned the InQL repo and executed the command, but I got an error. Later, I found there was no `setup.py` file in the InQL folder. I then went to the Python folder, ran the command, and it installed InQL, but I still couldn't access it. After that, I saw your note in `README.md`, so I downloaded the v4.0.7 source code zip file, extracted it, and installed it. Now I can use InQL, although I'm getting a warning like this:

```python
/usr/local/bin/inql:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('inql==4.0.7', 'inql')
usage: inql [-h] [-t TARGET] [-f SCHEMA_JSON_FILE] [-k KEY] [-p PROXY]
            [--header HEADERS HEADERS] [-d] [--no-generate-html]
            [--no-generate-schema] [--no-generate-queries]
            [--generate-cycles] [--cycles-timeout CYCLES_TIMEOUT]
            [--cycles-streaming] [--generate-tsv] [--insecure]
            [-o OUTPUT_DIRECTORY]

InQL Scanner
```

Is this normal, and why are we not using the latest version of InQL?

Thank you, Bro.

**Comment by dolevf** [comment]
Hi,

Seems normal to me, and shouldn't impact the tool.

The latest version if InQL has changed and no longer follows the patterns outlined in the book.

**Comment by RithvikTechnologies** [comment]
Is it necessary to mention the port number in the host name when using Graphoof to find GraphQL endpoints?
