### ISSUE TITLE
Lab os not downloading

### ISSUE THREAD

**Issue by HB-salman-SK** [dolevf/Black-Hat-GraphQL#3]
404 Not Found

![image](https://user-images.githubusercontent.com/59642335/225313024-4324a180-9656-46b6-9718-c6615c378a68.png)

can you pless lab download  url or any download link for os pless

**Comment by dolevf** [comment]
Just download the normal Kali linux from their website, it will still work

**Comment by HB-salman-SK** [comment]
I thought vulnhub was like Labs. Thanks for everything and thanks😍 🥰  again for Black-Hat-GraphQL Lab 💀 ☠️ 👽 👾.
