### ISSUE TITLE
Could you also write the Errata pages for iPad horizontal or vertical mode?

### ISSUE THREAD

**Issue by mrbiggleswirth** [dolevf/Black-Hat-GraphQL#6]
Hi Dolev Farhi & Nick Aleks, Great book!

I made the mistake of purchasing your book directly from Apple iTunes instead of from NoStarch website. So I don't have the PDF version of the book. : (

Could you guys in your **Errata page** also write the page number for iPad horizontal or vertical mode?

For example **Listing 4-14** you have written **page 83**. But iPad horizontal mode it is **page 85** and vertical mode is **page 103**.
So when you mention Errata at page 112 without any Listing numbers I can't pinpoint the text directly on my iPad.

Best Regards

**Comment by dolevf** [comment]
Thank you for mentioning this, @mrbiggleswirth!

I imagine that  change depending on the device you are using. Are you looking at the actual page number (bottom right of each page) or the numbering of the page of the file itself that the book viewer shows you? because they usually differ.

**Comment by mrbiggleswirth** [comment]
Hi @dolevf 

You are right Apple's app **"Books"** which uses EPUB files instead of PDF files re-calculates the page numbers and index table depending on the size of the screen and device.

I checked on some other book I purchased from NoStarch in the past. Where I got the book in 3 different formats (PDF, Mobi, EPUB), and the EPUB page numbers changes when I look at my iPad and iPhone both in vertical mode.

On the iPad my EPUB book doesn't show any static page numbers to the bottom right of each page. It's a dynamically calculated page number at the bottom center of the page.



If I show your **Support Team** my Apple iTunes purchase history and Apple invoice/receipt email. Could I perhaps get a discount at NoStarch to purchase the PDF version of your book? Instead of having to buy it twice to get the book in both EPUB and PDF versions.

https://nostarch.com/black-hat-graphql

**Comment by mrbiggleswirth** [comment]
@dolevf Never mind, I solved the mystery!

**"Apple Books"** > Contents > Page (drop-down arrow) > Page Numbers > "Digital Book" OR **"Print Edition"**

Selecting **"Print Edition"** solves the page numbering issues. Sometimes the page numbers are off, but only by 1 page. It's good enough, cheers!

**Comment by dolevf** [comment]
That's pretty cool. Thanks for sharing the solution.
