### ISSUE TITLE
Ch 8 page 209 Listing 8-5; Can't make the commix command work.

### ISSUE THREAD

**Issue by mrbiggleswirth** [dolevf/Black-Hat-GraphQL#8]
Hi,

On chapter 8 page 209 Listing 8-5, I can't make the example commix command work against the DVGA webapp. I'm not getting the same CLI questions when running commix compared to the book's example in Listing 8-5. I'm wondering which version of commix did you guys use for the book?

My Kali Linux apt install used commix `v3.7`. When I uninstalled commix from apt and instead installed commix from their git repo. I had installed commix `v3.8-dev#44`. But both versions still gave me issues when trying to perform the book's Listing 8-5 CLI example.

I don't understand what I'm doing wrong, did I mistype some characters, or did commix's latest versions break this example command?

```
# Trial 1
$ sudo commix --url="http://127.0.0.1:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test\")}"}' -p arg

# Trial 2
$ sudo commix --url="http://localhost:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test\")}"}' -p arg

# Trial 3
$ sudo commix --url="http://127.0.0.1:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test \")}"}' -p arg --level=2

# Trial 4
$ python3 commix.py --url="http://127.0.0.1:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test\")}"}' -p arg


# ERROR for all these tests, commix says that it didn't find any injection vulnerabilities with the arg entry point.
```

**Comment by mathdeziel** [comment]
I haven't pushed my analysis too far as too _why_ this happens, but removing the `-p arg` seems to work.

Try running `commix --url="http://127.0.0.1:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test \")}"}'`.

commix seems to be smart enough to detect where the injection should take place.

**Comment by mrbiggleswirth** [comment]
@mathdeziel Thanks, it worked!
Do you know why the space character is important for the FUZZ placeholder `\"test \"`?

```
$ pwd
# /home/kali/pentest_tools/commix/commix

$ python3 commix.py --url="http://127.0.0.1:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test \")}"}'
$ python3 commix.py --url="http://127.0.0.1:5013/graphql" --data='{"query":"query{systemDebug(arg:\"test\")}"}'

# SUCCESS for both commands!!
```

**Comment by mathdeziel** [comment]
@mrbiggleswirth The space character doesn't seem to be important/required.  As you have seen with your tests, the command will work just fine with and without.  There is a space in the book, but generally there isn't one in commix's documentation.  I assume the space would get removed during the fuzzing process anyways.

**Comment by mrbiggleswirth** [comment]
@mathdeziel Ok, thanks!
Should I close this ticket or do you guys want to keep the ticket open?

**Comment by dolevf** [comment]
If this was resolved, I'll close the issue. 

Thanks for sharing the solutions, we highly appreciate it.
